### ISSUE TITLE
scadapass - updated

### ISSUE THREAD

**Issue by scadadefender** [ITI/ICS-Security-Tools#10]
updated passwords were just released by SCADA Strangelove

https://github.com/scadastrangelove/SCADAPASS

[SCADAPASS-master.zip](https://github.com/ITI/ICS-Security-Tools/files/139315/SCADAPASS-master.zip)

**Comment by timyardley** [comment]
Addressed with commit d19030409ef673d1babc55d1b906eae49ac2d456

Thanks!
