### ISSUE TITLE
Quickdraw Modbus pcap 

### ISSUE THREAD

**Issue by NowhereToRun** [ITI/ICS-Security-Tools#14]
These traffic is normal or abnormal ?
If its abnormal, where can i get an abnormal list?
Thank you!

**Comment by timyardley** [comment]
Check out the modbus rules file here: https://github.com/digitalbond/quickdraw

**Comment by timyardley** [comment]
I've now provided that link in commit 62a71394d8a94540b00c659e3ddb4d969e5f6d77
