### ISSUE TITLE
Modbus capture in profinet folder?

### ISSUE THREAD

**Issue by JesApp** [ITI/ICS-Security-Tools#30]
So far as I can tell, the file [mb2.pcap](https://github.com/ITI/ICS-Security-Tools/blob/master/pcaps/profinet/mb2.pcap) in the `pcaps/profinet/` directory actually contains Modbus/TCP packets, not profinet.

Unless I'm incorrect, please move it.

**Comment by jmj** [comment]
Feel free to create and submit a merge request with the changes

**Comment by JesApp** [comment]
There you go. :)

**Comment by timyardley** [comment]
Merged. Thanks!
