### ISSUE TITLE
profinet write request packet capture

### ISSUE THREAD

**Issue by royenf2327** [ITI/ICS-Security-Tools#39]
i have been developing a means to read from and write to holding registers of a Device through Profinet Protocol,

regarding the same i have been able to 
1. find a device on the network through PN-DCP
2. get/set device parameters
3. Connect to IO of a device sending aconnect request and recieved a response thus, being allocated a new AR.
3. Read a specific api/slot/subslot  through PNIO-cm(with your help)

to do: write to a particular api/slot/subslot.

dependency: i could not form a packet to do the same having all properties at hand
help required: if you could please upload a sample write request packet capture as a .pcap file, i would be able to do that.

Look Forward to responses from all sides.

Thanks

**Comment by timyardley** [comment]
Sorry, this is really about collecting items from around the internet. I contribute things that I have handy, but this isn't one of the items that I have handy. Sorry.
