### ISSUE TITLE
Wireshark missing

### ISSUE THREAD

**Issue by edoardottt** [ITI/ICS-Security-Tools#47]
**Is your feature request related to a problem? Please describe.**
I can't see Wireshark in this list...why?

**Describe the solution you'd like**
Add WireShark to this repo (or explain me why it's missing)

**Describe alternatives you've considered**
Maybe there is a specific reason because it's missing

**Additional context**

**Comment by timyardley** [comment]
There are a bunch of wireshark related items throughout the repo... for instance, protocol specific aspects are here:

https://github.com/ITI/ICS-Security-Tools/blob/c29c0b82052e74648a6f26b9e53055594358308d/protocols/README.md
