### ISSUE TITLE
pcap organization

### ISSUE THREAD

**Issue by jadamcrain** [ITI/ICS-Security-Tools#7]
ATM, pcaps are just tossed into folders based on where they came from, rather than organized by protocol. 

I have a wide swath of DNP3 pcaps I'd like to add to this that were recorded for validating parsers/firewalls. Where should they go?

Would you accept a pull request if I reorganized the existing pcaps by protocol, instead of by "where they came from"?

**Comment by timyardley** [comment]
Yeah, I just dumped some in and put them under where they came from. There are benefits and drawbacks to "by source" and "by protocol". The "by source" approach provides direct attribution as to where they came from (and likely what they may have been used for). The "by protocol" approach provides the benefit of organizing based on the protocol (which is likely of more direct use to people). 

I am fine with either approach. A hybrid would be to organize it by source, and then sub-categorize it by protocol.

Do whatever you think will have more value and we'll merge it in.

**Comment by timyardley** [comment]
Addressed by adding this: https://github.com/ITI/ICS-Security-Tools/commit/b4d2cdeb2a07acd06c6d7660fa5c29d90701c5c5

Which links to Jason's repository of organized ICS PCAPs... https://github.com/automayt/ICS-pcap

Closing this issue.
