### ISSUE TITLE
Molex EIP tool

### ISSUE THREAD

**Issue by tlf30** [ITI/ICS-Security-Tools#87]
A great tool for EIP is the free molex EIP tool. It can be used to send EIP messages to a device for testing. This is a free tool for anyone to download. 

https://www.molex.com/mx_upload/superfamily/iccc/EtherNet_IPTool.html

**Comment by timyardley** [comment]
Feel free to submit a PR to get it included. Otherwise I will look to add it when I have a chance.

**Comment by timyardley** [comment]
added here: https://github.com/ITI/ICS-Security-Tools/commit/23e3c6acead2a6215692cb7ff1dededab2eb7a9b
